### ISSUE TITLE
Here is how you fix the transaction spam

### ISSUE THREAD

**Issue by researcher987654321** [dogechain-lab/dogechain#158]
Dogechain is seeing massive transaction spam. Why are people spamming the chain? Because transactions are ordered randomly so arbitrage bots are incentivized to send in as many instances of the same function call (with different accounts) as possible.

See the same issue in Harmony. As soon as they fixed that, the spam went away. https://github.com/harmony-one/harmony/issues/4113

If you don't do this, not only will this get much worse in the upcoming days, but you will also see massive number of wallets created just for spamming. And your chain's data snapshot size (currently growing at ~8GB per day?) will grow unimaginably because of the sheer number of transactions.

**Comment by DarianShawn** [comment]
🙌 A great advice!

We do value transactions on price when building block. And try to add more pruning features, which is still in test.
Refactor the whole `txpool` would take a long time, so we take small steps here.

The db size is not our most emergency right now, since the db size is 70GB for a month or so. The snapshot repo, db compression, and some other features could reduce this problem. They are all in plan.

Any code contribution is welcome if you like. 🙏
A small step of you, a great step for Dogechain.

**Comment by DarianShawn** [comment]
After some discussions, we'll try to adopt this solution.
But it will be included in the next one or two milestone.
We are focusing on memory consuming issues.

👍🏻Thanks for your wonderful advice. @researcher987654321
