### ISSUE TITLE
Unstable websocket endpoint

### ISSUE THREAD

**Issue by wdcs-amitkumar** [dogechain-lab/dogechain#275]
```wss://rpc-testnet.dogechain.dog```

Above websocket endpoint is not stable.
I find it difficult to connect my rust client to listen to smart contract events using above endpoint.

Please provide a stable one ....
Premium or free both works.

Thanks!!

**Comment by DarianShawn** [comment]
We discontinued the public official WebSocket endpoints for TestNet and MainNet a long time ago.
The reason is simple: long-term network connections are resource-intensive, and the cost of providing sufficient and stable WS endpoints is too high.
Private nodes should be maintained by the community to mitigate the risk of public rpc nodes being attacked.

**Comment by DarianShawn** [comment]
Close it due to long inactivation.
